config/routes.rb
Playmysong::Application.routes.draw do
  resources :votes

  resources :audience_members
    
  get '/home' => 'public#index'

  get '/welcome' => 'welcome#landing'
  post '/welcome' => 'welcome#event_lookup', :as => 'event_lookup'
  get '/events/:id/live_admin' => 'events#live_event_admin', :as => 'live_event_admin'
  post '/set_items/:id' => 'set_items#play_song', :as => 'play_song'
  resources :set_items

  resources :events

  devise_for :users
  resources :songs

  root 'public#index'

  get ':code' => 'events#live_event', :as => 'live_event'

end

app/models/event.rb
class Event < ActiveRecord::Base
  include Codeable

  has_many :set_items, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :audience_members, through: :votes
  belongs_to :user
  has_many :songs, through: :set_items

  validates :venue, :date, presence: true
  validates :code, uniqueness: true
  validates :venue, uniqueness: { scope: :date, case_sensitive: false }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, :only => :live_event
  before_action :set_event, only: [:show, :edit, :update, :destroy, :live_event_admin]

  # GET /events
  # GET /events.json
  def index
    @title = "Events"
    @events = Event.where(user_id: current_user.id).order('date')
    @event = Event.new
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @set_items = @event.set_items
    @songs = current_user.songs.order('artist, title').find(:all, conditions: ['id not in (?)', @set_items.map(&:song_id)])
    if @set_items.empty?
      @songs = current_user.songs.order('artist, title')
    end
  end

  # GET /events/new
  # def new
  #   @event = Event.new
  # end

  # GET /events/1/edit
  def edit
  end

  def live_event
    @event = Event.find_by(code: params[:code])
    @set_items = @event.set_items.order("vote_count DESC")
    audience_member_vote_count = Vote.where("event_id = ? AND audience_member_id = ?", @event.id, session[:audience_member_id]).count
    @remaining_votes = (5 - audience_member_vote_count)
  end

  def live_event_admin
    @set_items = @event.set_items.order("vote_count DESC")
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { redirect_to events_url, notice: "Please provide both Venue and Date and make sure they're unique." }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:venue, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :venue, :placeholder => 'Event Venue' %>
  </div>

  <div class="field">
    <%= f.date_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="devise-form">
	
<h1>Editing event</h1>

<%= render 'form' %>

</section>

app/views/events/index.html.erb
<section class="events">

<h1>Events</h1>

<section class="index-form group">
	<legend>New Event</legend>
<%= render 'form' %>
</section>

<table>
  <thead>
    <tr>
      <th width="30%">Venue</th>
      <th width="15%">Date</th>
      <th width="15%">Event Code</th>
      <th width="40%">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.venue %></td>
        <td><%= event.date.strftime('%a %b %e, %Y') %></td>
        <td><%= event.code %></td>
        <td><%= link_to "Launch Event", live_event_admin_path(event) %>
        <%= link_to 'Manage Set List', event %>
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</section>

app/views/events/live_event.html.erb
<section class="live group">


<h1><%= @event.user.artist %></h1>
  <h2>Requests Remaining</h2>
  <p><%= @remaining_votes %></p>





	<% @set_items.each do |set_song| %>
	<div class="live-vote group">
		<dl class="group">
  <dt>Song</dt>
    <dd><%= set_song.song.title %></dd>
    </dl>
    <dl class="group">
  <dt>Artist</dt>
    <dd><%= set_song.song.artist %></dd>
    </dl>
    <dl class="group">
  <dt>Requests</dt>
    <dd><%= set_song.vote_count %></dd>
</dl>
		<p><%= button_to "Request This Song", controller: "votes", action: "create", set_item_id: set_song.id, audience_member_id: session[:audience_member_id], event_id: set_song.event_id %></p>
		</div>
	<% end %>
</section>

app/views/events/live_event_admin.html.erb
<section class="live-admin">
<h1>Live Dashboard</h1>


<table>
  <thead>
    <tr>
      <th width="25%">Title</th>
      <th width="25%">Artist</th>
      <th width="15%">Requests</th>
      <th width="15%">Play Count</th>
      <th width="20%"></th>
    </tr>
  </thead>

  <tbody>
    <% @set_items.each do |set_song| %>
      <tr>
        <td><%= set_song.song.title %></td>
        <td><%= set_song.song.artist %></td>
        <td><%= set_song.vote_count %></td>
        <td><%= set_song.play_count %></td>
        <td><%= button_to 'Play Song', play_song_path(set_song) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>

app/views/events/new.html.erb
<section>
	
<h1>New event</h1>

<%= render 'form' %>

</section>

app/views/events/show.html.erb
<section class="event group">

<h1>Manage Set List</h1>

<section class="song-list group">
	<h2>Song List</h2>
	<table>
  <thead>
    <tr>
     <th width="30%"></th>
      <th width="35%">Title</th>
      <th width="35%">Artist</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td>
          <%= form_tag set_items_path do %>
            <%= hidden_field_tag :event_id, @event.id %>
            <%= hidden_field_tag :song_id, song.id %>
            <%= button_tag 'Add Song' %>
          <% end %>
        </td>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>

<section class="set-list group">
	<h2>Set List</h2>
	<table>
  <thead>
    <tr>
      <th width="30%"></th>
      <th width="35%">Title</th>
      <th width="35%">Artist</th>
    </tr>
  </thead>

  <tbody>
    <% @set_items.each do |set_song| %>
      <tr>
      	<td><%= button_to 'Remove', set_item_path(set_song), method: :delete %></td>
        <td><%= set_song.song.title %></td>
        <td><%= set_song.song.artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>








</section>