config/routes.rb
Playmysong::Application.routes.draw do
  resources :votes

  resources :audience_members
    
  get '/home' => 'public#index'

  get '/welcome' => 'welcome#landing'
  post '/welcome' => 'welcome#event_lookup', :as => 'event_lookup'
  get '/events/:id/live_admin' => 'events#live_event_admin', :as => 'live_event_admin'
  post '/set_items/:id' => 'set_items#play_song', :as => 'play_song'
  resources :set_items

  resources :events

  devise_for :users
  resources :songs

  root 'public#index'

  get ':code' => 'events#live_event', :as => 'live_event'

end

app/models/audience_member.rb
class AudienceMember < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  belongs_to :event
end

app/controllers/audience_members_controller.rb
class AudienceMembersController < ApplicationController
  before_action :set_audience_member, only: [:show, :edit, :update, :destroy]

  # GET /audience_members
  # GET /audience_members.json
  # def index
  #   @audience_members = AudienceMember.all
  # end

  # GET /audience_members/1
  # GET /audience_members/1.json
  # def show
  # end

  # GET /audience_members/new
  # def new
  #   @audience_member = AudienceMember.new
  # end

  # GET /audience_members/1/edit
  # def edit
  # end

  # POST /audience_members
  # POST /audience_members.json
  # def create
  #   @audience_member = AudienceMember.new(audience_member_params)

  #   respond_to do |format|
  #     if @audience_member.save
  #       format.html { redirect_to @audience_member, notice: 'Audience member was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @audience_member }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @audience_member.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /audience_members/1
  # PATCH/PUT /audience_members/1.json
  # def update
  #   respond_to do |format|
  #     if @audience_member.update(audience_member_params)
  #       format.html { redirect_to @audience_member, notice: 'Audience member was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @audience_member.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /audience_members/1
  # DELETE /audience_members/1.json
  # def destroy
  #   @audience_member.destroy
  #   respond_to do |format|
  #     format.html { redirect_to audience_members_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audience_member
      @audience_member = AudienceMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audience_member_params
      params.require(:audience_member).permit(:email)
    end
end

app/helpers/audience_members_helper.rb
module AudienceMembersHelper
end

app/views/audience_members/_form.html.erb
<%= form_for(@audience_member) do |f| %>
  <% if @audience_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audience_member.errors.count, "error") %> prohibited this audience_member from being saved:</h2>

      <ul>
      <% @audience_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audience_members/edit.html.erb
<h1>Editing audience_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @audience_member %> |
<%= link_to 'Back', audience_members_path %>

app/views/audience_members/index.html.erb
<h1>Listing audience_members</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @audience_members.each do |audience_member| %>
      <tr>
        <td><%= audience_member.email %></td>
        <td><%= link_to 'Show', audience_member %></td>
        <td><%= link_to 'Edit', edit_audience_member_path(audience_member) %></td>
        <td><%= link_to 'Destroy', audience_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audience member', new_audience_member_path %>

app/views/audience_members/new.html.erb
<h1>New audience_member</h1>

<%= render 'form' %>

<%= link_to 'Back', audience_members_path %>

app/views/audience_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @audience_member.email %>
</p>

<%= link_to 'Edit', edit_audience_member_path(@audience_member) %> |
<%= link_to 'Back', audience_members_path %>