config/routes.rb
Playmysong::Application.routes.draw do
  resources :votes

  resources :audience_members
    
  get '/home' => 'public#index'

  get '/welcome' => 'welcome#landing'
  post '/welcome' => 'welcome#event_lookup', :as => 'event_lookup'
  get '/events/:id/live_admin' => 'events#live_event_admin', :as => 'live_event_admin'
  post '/set_items/:id' => 'set_items#play_song', :as => 'play_song'
  resources :set_items

  resources :events

  devise_for :users
  resources :songs

  root 'public#index'

  get ':code' => 'events#live_event', :as => 'live_event'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :audience_member
  belongs_to :set_item
  belongs_to :event

  validate :user_can_only_vote_5_times

  after_create :add_to_vote_count

  after_destroy :deduct_from_vote_count

  def user_can_only_vote_5_times
    vote = Vote.where("event_id = ? AND audience_member_id = ?", self.event_id, self.audience_member_id)
    if vote.count >= 5
      errors.add(:base, "You can't vote anymore.")
    end
  end

  def add_to_vote_count
    self.set_item.vote_count += 1
    self.set_item.save
  end

  def deduct_from_vote_count
    self.set_item.vote_count -= 1
    self.set_item.save
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  # def index
  #   @votes = Vote.all
  # end

  # GET /votes/1
  # GET /votes/1.json
  # def show
  # end

  # GET /votes/new
  # def new
  #   @vote = Vote.new
  # end

  # GET /votes/1/edit
  # def edit
  # end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new
    set_item = SetItem.find_by(id: params[:set_item_id])
    @vote.set_item_id = params[:set_item_id]
    @vote.audience_member_id = params[:audience_member_id]
    @vote.event_id = params[:event_id]


    respond_to do |format|
      if @vote.save
        format.html { redirect_to live_event_url(set_item.event.code) }
        format.json { render action: 'show', status: :created, location: @vote }
      else
        format.html { redirect_to live_event_url(set_item.event.code) }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  # def update
  #   respond_to do |format|
  #     if @vote.update(vote_params)
  #       format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @vote.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /votes/1
  # DELETE /votes/1.json
  # def destroy
  #   @vote.destroy
  #   respond_to do |format|
  #     format.html { redirect_to votes_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:audience_member_id, :set_item_id)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :audience_member %><br>
    <%= f.text_field :audience_member %>
  </div>
  <div class="field">
    <%= f.label :set_item %><br>
    <%= f.text_field :set_item %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>Audience member</th>
      <th>Set item</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.audience_member %></td>
        <td><%= vote.set_item %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Audience member:</strong>
  <%= @vote.audience_member %>
</p>

<p>
  <strong>Set item:</strong>
  <%= @vote.set_item %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>