config/routes.rb
Playmysong::Application.routes.draw do
  resources :votes

  resources :audience_members
    
  get '/home' => 'public#index'

  get '/welcome' => 'welcome#landing'
  post '/welcome' => 'welcome#event_lookup', :as => 'event_lookup'
  get '/events/:id/live_admin' => 'events#live_event_admin', :as => 'live_event_admin'
  post '/set_items/:id' => 'set_items#play_song', :as => 'play_song'
  resources :set_items

  resources :events

  devise_for :users
  resources :songs

  root 'public#index'

  get ':code' => 'events#live_event', :as => 'live_event'

end

app/models/set_item.rb
class SetItem < ActiveRecord::Base
  belongs_to :song
  belongs_to :event
  has_many :votes, dependent: :destroy
end

app/controllers/set_items_controller.rb
class SetItemsController < ApplicationController
  skip_before_action :authenticate_user!, :only => :update
  before_action :set_set_item, only: [:update, :play_song]

  # GET /set_items
  # GET /set_items.json
  # def index
  #   @set_items = SetItem.all
  # end

  # GET /set_items/1
  # GET /set_items/1.json
  # def show
  # end

  # GET /set_items/new
  # def new
  #   @set_item = SetItem.new
  # end

  # GET /set_items/1/edit
  # def edit
  # end

  # POST /set_items
  # POST /set_items.json
  def create
    @set_item = SetItem.new(set_item_params)

    @set_item.vote_count = 0
    @set_item.play_count = 0
    respond_to do |format|
      if @set_item.save
        format.html { redirect_to event_url(params[:event_id]) }
        format.json { render action: 'show', status: :created, location: @set_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @set_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_items/1
  # PATCH/PUT /set_items/1.json
  def update
    @set_item.vote_count += 1
    @set_item.save
    redirect_to live_event_path(@set_item.event.code)
    # respond_to do |format|
    #   if @set_item.update(set_item_params)
    #     format.html { redirect_to @set_item, notice: 'Set item was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @set_item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def play_song
    @set_item.votes.destroy_all
    @set_item.play_count += 1
    @set_item.save
    redirect_to live_event_admin_url(@set_item.event_id)
  end

  # DELETE /set_items/1
  # DELETE /set_items/1.json
  def destroy
    @set_item = SetItem.find(params[:id])
    @set_item.destroy
    respond_to do |format|
      format.html { redirect_to event_url(@set_item.event_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_set_item
      @set_item = SetItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_item_params
      params.permit(:song_id, :event_id)
    end
end

app/helpers/set_items_helper.rb
module SetItemsHelper
end

app/views/set_items/_form.html.erb
<%= form_for(@set_item) do |f| %>
  <% if @set_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@set_item.errors.count, "error") %> prohibited this set_item from being saved:</h2>

      <ul>
      <% @set_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song %><br>
    <%= f.text_field :song %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :votes %><br>
    <%= f.number_field :votes %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/set_items/edit.html.erb
<h1>Editing set_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @set_item %> |
<%= link_to 'Back', set_items_path %>

app/views/set_items/index.html.erb
<h1>Listing set_items</h1>

<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>Event</th>
      <th>Votes</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @set_items.each do |set_item| %>
      <tr>
        <td><%= set_item.song %></td>
        <td><%= set_item.event %></td>
        <td><%= set_item.votes %></td>
        <td><%= set_item.active %></td>
        <td><%= link_to 'Show', set_item %></td>
        <td><%= link_to 'Edit', edit_set_item_path(set_item) %></td>
        <td><%= link_to 'Destroy', set_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Set item', new_set_item_path %>

app/views/set_items/new.html.erb
<h1>New set_item</h1>

<%= render 'form' %>

<%= link_to 'Back', set_items_path %>

app/views/set_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @set_item.song %>
</p>

<p>
  <strong>Event:</strong>
  <%= @set_item.event %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @set_item.votes %>
</p>

<p>
  <strong>Active:</strong>
  <%= @set_item.active %>
</p>

<%= link_to 'Edit', edit_set_item_path(@set_item) %> |
<%= link_to 'Back', set_items_path %>